### ISSUE TITLE
/opt/copilot/scripts/startup.sh: Permission denied

### ISSUE THREAD

**Issue by bjorntheart** [bvtujo/copilot-wordpress#1]
I've run into the following issue which causes the service to not reach a healthy state
```
$ copilot svc logs

Found only one deployed service xxx-dev in environment test
copilot/xxx-dev/f2 /bin/sh: 1: /opt/copilot/scripts/startup.sh: Permission denied
copilot/xxx-dev/c4 /bin/sh: 1: /opt/copilot/scripts/startup.sh: Permission denied
copilot/xxx-dev/af /bin/sh: 1: /opt/copilot/scripts/startup.sh: Permission denied
copilot/xxx-dev/a1 /bin/sh: 1: /opt/copilot/scripts/startup.sh: Permission denied
copilot/xxx-dev/b6 /bin/sh: 1: /opt/copilot/scripts/startup.sh: Permission denied
copilot/xxx-dev/ac /bin/sh: 1: /opt/copilot/scripts/startup.sh: Permission denied
```
_note: service name redacted_

**Comment by TavolettaP** [comment]
> I've run into the following issue which causes the service to not reach a healthy state
> 
> ```
> $ copilot svc logs
> 
> Found only one deployed service xxx-dev in environment test
> copilot/xxx-dev/f2 /bin/sh: 1: /opt/copilot/scripts/startup.sh: Permission denied
> copilot/xxx-dev/c4 /bin/sh: 1: /opt/copilot/scripts/startup.sh: Permission denied
> copilot/xxx-dev/af /bin/sh: 1: /opt/copilot/scripts/startup.sh: Permission denied
> copilot/xxx-dev/a1 /bin/sh: 1: /opt/copilot/scripts/startup.sh: Permission denied
> copilot/xxx-dev/b6 /bin/sh: 1: /opt/copilot/scripts/startup.sh: Permission denied
> copilot/xxx-dev/ac /bin/sh: 1: /opt/copilot/scripts/startup.sh: Permission denied
> ```
> 
> _note: service name redacted_

Hello! Did you find a solution for this problem? I'm stuck in the same situation.

**Comment by bjorntheart** [comment]
The `startup.sh` should be made executable
